name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Testing

    runs-on: ubuntu-latest

    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

        with:
          node-version: 16

      - name: Run tests
        run: npx cloud test
